#!/usr/bin/python3

import sys
import os
import base64

POSITIONAL_ARGUMENTS = 1
GDBSERVER_PORT = 1234
DOCKER_PATH = "./"
HELP = '''
Usage: docker-debugger /path/to/challenge/binary/in/docker


OPTIONS:
    -r --restore-backup: restore the backups (Usable only if there are Dockerfile.bak and dokcer-compose.bak files)
    -u --docker-path: path to the Dokcerfile and docker-compose.yml (default: ./)
    -p --port: port where gdbserver will listen (default: 1234)
    -h --help: print this message
'''
CHALLENGE_PATH = ""
BINARY_NAME = "debugging_bin"
BINARY = b"f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAA4BIAAAAAAABAAAAAAAAAANA6AAAAAAAAAAAAAEAAOAANAEAAHwAeAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAKAAAAAAAA8AoAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAA1QkAAAAAAADVCQAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAABsAgAAAAAAAGwCAAAAAAAAABAAAAAAAAABAAAABgAAABgtAAAAAAAAGD0AAAAAAAAYPQAAAAAAAAgDAAAAAAAAGAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAAKC0AAAAAAAAoPQAAAAAAACg9AAAAAAAA8AEAAAAAAADwAQAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAAUIQAAAAAAABQhAAAAAAAAFCEAAAAAAABMAAAAAAAAAEwAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAAGC0AAAAAAAAYPQAAAAAAABg9AAAAAAAA6AIAAAAAAADoAgAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAAAQAAAAAAAAAEAAAAFAAAAAMAAABHTlUAm//Mpa4zPcBP3aAZ0h5fKGd8D78EAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAACAAAAGgAAAAEAAAAGAAAAAACBAAABEAAaAAAAAAAAACgdjBzRZc5tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAzwAAACAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAABIAAAAAAAAAAAAAAAAAAAAAAAAADgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAJAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAPAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAhAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAkQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAnwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA6wAAACAAAAAAAAAAAAAAAAAAAAAAAAAAiwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAVAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAbQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAlwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAbwAAABIAAAAAAAAAAAAAAAAAAAAAAAAABwAAABIAAAAAAAAAAAAAAAAAAAAAAAAASAAAABIAAAAAAAAAAAAAAAAAAAAAAAAATwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAgwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAHwAAABIAAAAAAAAAAAAAAAAAAAAAAAAA+gAAACAAAAAAAAAAAAAAAAAAAAAAAAAAKwAAABIAAAAAAAAAAAAAAAAAAAAAAAAANQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAQQAAABEAGgAgQAAAAAAAAAgAAAAAAAAAdAAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAGZnZXRzAHBlcnJvcgBfX3N0YWNrX2Noa19mYWlsAGV4aXQAc2V0YnVmAGZvcmsAcmVhZABzdHJzdHIAZHVwMgBzdGRvdXQAZXhlY3ZwAGF0b2kAbWFsbG9jAF9fbGliY19zdGFydF9tYWluAGZkb3BlbgBfX2N4YV9maW5hbGl6ZQBzcHJpbnRmAGtpbGwAZmNsb3NlAHdhaXRwaWQAcGlwZQBsaWJjLnNvLjYAR0xJQkNfMi40AEdMSUJDXzIuMi41AEdMSUJDXzIuMzQAX0lUTV9kZXJlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fZ21vbl9zdGFydF9fAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAAAACAAEAAwAEAAMAAwADAAMAAwADAAMAAQADAAMAAwADAAMAAwADAAMAAwADAAEAAwADAAMAAwAAAAAAAQADAKQAAAAQAAAAAAAAABRpaQ0AAAQArgAAABAAAAB1GmkJAAADALgAAAAQAAAAtJGWBgAAAgDEAAAAAAAAABg9AAAAAAAACAAAAAAAAADAEwAAAAAAACA9AAAAAAAACAAAAAAAAACAEwAAAAAAAAhAAAAAAAAACAAAAAAAAAAIQAAAAAAAABhAAAAAAAAACAAAAAAAAAAIIAAAAAAAANg/AAAAAAAABgAAAAEAAAAAAAAAAAAAAOA/AAAAAAAABgAAAAIAAAAAAAAAAAAAAOg/AAAAAAAABgAAAAwAAAAAAAAAAAAAAPA/AAAAAAAABgAAABcAAAAAAAAAAAAAAPg/AAAAAAAABgAAABsAAAAAAAAAAAAAACBAAAAAAAAABQAAABoAAAAAAAAAAAAAADA/AAAAAAAABwAAAAMAAAAAAAAAAAAAADg/AAAAAAAABwAAAAQAAAAAAAAAAAAAAEA/AAAAAAAABwAAAAUAAAAAAAAAAAAAAEg/AAAAAAAABwAAAAYAAAAAAAAAAAAAAFA/AAAAAAAABwAAAAcAAAAAAAAAAAAAAFg/AAAAAAAABwAAAAgAAAAAAAAAAAAAAGA/AAAAAAAABwAAAAkAAAAAAAAAAAAAAGg/AAAAAAAABwAAAAoAAAAAAAAAAAAAAHA/AAAAAAAABwAAAAsAAAAAAAAAAAAAAHg/AAAAAAAABwAAAA0AAAAAAAAAAAAAAIA/AAAAAAAABwAAAA4AAAAAAAAAAAAAAIg/AAAAAAAABwAAAA8AAAAAAAAAAAAAAJA/AAAAAAAABwAAABAAAAAAAAAAAAAAAJg/AAAAAAAABwAAABEAAAAAAAAAAAAAAKA/AAAAAAAABwAAABIAAAAAAAAAAAAAAKg/AAAAAAAABwAAABMAAAAAAAAAAAAAALA/AAAAAAAABwAAABQAAAAAAAAAAAAAALg/AAAAAAAABwAAABUAAAAAAAAAAAAAAMA/AAAAAAAABwAAABYAAAAAAAAAAAAAAMg/AAAAAAAABwAAABgAAAAAAAAAAAAAANA/AAAAAAAABwAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wISIsF2S8AAEiFwHQC/9BIg8QIwwAAAAAA/zX6LgAA/yX8LgAADx9AAPMPHvpoAAAAAOni////ZpDzDx76aAEAAADp0v///2aQ8w8e+mgCAAAA6cL///9mkPMPHvpoAwAAAOmy////ZpDzDx76aAQAAADpov///2aQ8w8e+mgFAAAA6ZL///9mkPMPHvpoBgAAAOmC////ZpDzDx76aAcAAADpcv///2aQ8w8e+mgIAAAA6WL///9mkPMPHvpoCQAAAOlS////ZpDzDx76aAoAAADpQv///2aQ8w8e+mgLAAAA6TL///9mkPMPHvpoDAAAAOki////ZpDzDx76aA0AAADpEv///2aQ8w8e+mgOAAAA6QL///9mkPMPHvpoDwAAAOny/v//ZpDzDx76aBAAAADp4v7//2aQ8w8e+mgRAAAA6dL+//9mkPMPHvpoEgAAAOnC/v//ZpDzDx76aBMAAADpsv7//2aQ8w8e+mgUAAAA6aL+//9mkPMPHvr/JW4uAABmDx9EAADzDx76/yWWLQAAZg8fRAAA8w8e+v8lji0AAGYPH0QAAPMPHvr/JYYtAABmDx9EAADzDx76/yV+LQAAZg8fRAAA8w8e+v8ldi0AAGYPH0QAAPMPHvr/JW4tAABmDx9EAADzDx76/yVmLQAAZg8fRAAA8w8e+v8lXi0AAGYPH0QAAPMPHvr/JVYtAABmDx9EAADzDx76/yVOLQAAZg8fRAAA8w8e+v8lRi0AAGYPH0QAAPMPHvr/JT4tAABmDx9EAADzDx76/yU2LQAAZg8fRAAA8w8e+v8lLi0AAGYPH0QAAPMPHvr/JSYtAABmDx9EAADzDx76/yUeLQAAZg8fRAAA8w8e+v8lFi0AAGYPH0QAAPMPHvr/JQ4tAABmDx9EAADzDx76/yUGLQAAZg8fRAAA8w8e+v8l/iwAAGYPH0QAAPMPHvr/JfYsAABmDx9EAADzDx76Me1JidFeSIniSIPk8FBURTHAMclIjT3KAwAA/xXTLAAA9GYuDx+EAAAAAABIjT0JLQAASI0FAi0AAEg5+HQVSIsFtiwAAEiFwHQJ/+APH4AAAAAAww8fgAAAAABIjT3ZLAAASI010iwAAEgp/kiJ8EjB7j9IwfgDSAHGSNH+dBRIiwWFLAAASIXAdAj/4GYPH0QAAMMPH4AAAAAA8w8e+oA9nSwAAAB1K1VIgz1iLAAAAEiJ5XQMSIs9ZiwAAOjZ/f//6GT////GBXUsAAABXcMPHwDDDx+AAAAAAPMPHvrpd/////MPHvpVSInlSIPsIIl97EiJdeCJ0IhF6GRIiwQlKAAAAEiJRfgxwMdF9AAAAABIjU3zi0XsugEAAABIic6Jx+jz/f//SIXAdCKLRfRIY9BIi0XgSAHCD7ZF84gCg0X0AQ+2RfM4Reh1xesBkItF9EiLVfhkSCsUJSgAAAB0BehU/f//ycPzDx76VUiJ5UiB7HABAACJvZz+//9IibWQ/v//ZEiLBCUoAAAASIlF+DHAx4Wg/v///////4uFnP7//4mFpP7//+nQAAAAi5Wk/v//SI2FsP7//0iNDbYLAABIic5Iice4AAAAAOjo/f//SI2FsP7//74AAAAASInHuAAAAADoj/3//4mFqP7//4O9qP7//wB4fEiNjfD+//+Lhaj+//+6AAAAAEiJzonH6M3+//+Jhaz+//+Lhaj+//+Jx+jR/P//g72s/v//AH5FSIuVkP7//0iNhfD+//9IidZIicfon/3//0iJwkiNhfD+//9IOcJ1HYuFpP7//zuFoP7//34Pi4Wk/v//iYWg/v//6wGQg4Wk/v//AYG9pP7///9/AAAPjiD///+LhaD+//9Ii1X4ZEgrFCUoAAAAdAXoEvz//8nD8w8e+lVIieVIg+xQiX28iXW4ZEiLBCUoAAAASIlF+DHAiwVZKgAAhcB+MosFTyoAAL4JAAAAicfoU/z//4XAdRyLBTkqAACJxkiNBY8KAABIice4AAAAAOjj+///6M78//+JRcyDfcwAD4WOAAAASI0FgwoAAEiJRdC/EAAAAOgc/P//SIlF2EiNBXQKAABIiUXgvxAAAADoA/z//0iJRehIi0Xoi1W8SI0NXQoAAEiJzkiJx7gAAAAA6FH8//9Ii0XYi1W4SI0NQgoAAEiJzkiJx7gAAAAA6DP8//9Ix0XwAAAAAEiNRdBIicZIjQUGCgAASInH6PX7///rJYtFzIkFeikAAIsFdCkAAInGSI0F/gkAAEiJx7gAAAAA6B77//+QSItF+GRIKwQlKAAAAHQF6Nn6///Jw/MPHvpVSInlSIHsUAQAAIm9vPv//0iJtbD7//9kSIsEJSgAAABIiUX4McBIiwUlKQAAvgAAAABIicfoqPr//4O9vPv//wF/GUiNBacJAABIicfoUPv//78BAAAA6Ib7//9Ii4Ww+///SItACEiJhdD7//9Ii4Ww+///SIPAEEiLAEiJx+g++///iYXE+///g73E+///AH4Mgb3E+/////8AAH4ZSI0FYQkAAEiJx+j0+v//vwEAAADoKvv//4uFvPv//4PoAkiYSMHgA0iJx+iT+v//SImF2Pv//8eFwPv//wMAAADrQouFwPv//0iYSI0UxQAAAABIi4Ww+///SAHQi5XA+///SGPSSMHiA0iNSuhIi5XY+///SAHKSIsASIkCg4XA+///AYuFwPv//zuFvPv//3ywi4W8+///SJhIweADSI1Q6EiLhdj7//9IAdBIxwAAAAAASI2F6Pv//0iJx+jA+f//6Iv6//+Jhcj7//+Dvcj7//8AdXOLhej7//+Jx+iP+f//i4Xs+///vgEAAACJx+hd+f//i4Xs+///vgIAAACJx+hL+f//i4Xs+///icfoXvn//0iLhdj7//9IiwBIi5XY+///SInWSInH6OL5//9IjQVFCAAASInH6MP5//+/AQAAAOj5+f//i4Xs+///icfoHPn//4uF6Pv//0iNFTIIAABIidaJx+hl+f//SImF4Pv//0iDveD7//8AdRlIjQUSCAAASInH6HX5//+/AQAAAOir+f//SIuF4Pv//74AAAAASInH6Jf4///rTIsFCycAAEiLldD7//9IidaJx+gc+///iYXM+///iwXuJgAAOYXM+///fiGLhcz7//+JBdomAACLlcT7//+Lhcz7//+J1onH6Cn8//9Ii5Xg+///SI2F8Pv//74ABAAASInH6I74//9IhcB1lEiLheD7//9Iicfo+vf//4uFyPv//7oAAAAAvgAAAACJx+ij+P//uAAAAABIi1X4ZEgrFCUoAAAAdAXo2vf//8nD8w8e+kiD7AhIg8QIwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAAAAAAAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoAL3Byb2MvJWQvY21kbGluZQBLaWxsZWQgZ2Ric2VydmVyIChQSUQ9JWQpAGdkYnNlcnZlcgAtLWF0dGFjaAAlZAA6JWQAU3RhcnRpbmcgZ2Ric2VydmVyIChQSUQ9JWQpAE5vdCBlbm91Z2ggYXJndW1lbnRzIQBJbnNlcnQgYSB2YWxpZCBwb3J0IQBCaW5hcnkgZXhlY3V0aW9uIGZhaWxlZCEAcgBmZG9wZW4gZmFpbGVkAAABGwM7SAAAAAgAAAAM7///fAAAAGzw//+kAAAAfPD//7wAAADM8f//ZAAAALXy///UAAAAOvP///QAAAB89P//FAEAALX1//80AQAAFAAAAAAAAAABelIAAXgQARsMBwiQAQAAFAAAABwAAABg8f//JgAAAABEBxAAAAAAJAAAADQAAACI7v//YAEAAAAOEEYOGEoPC3cIgAA/GjkqMyQiAAAAABQAAABcAAAAwO///xAAAAAAAAAAAAAAABQAAAB0AAAAuO///1ABAAAAAAAAAAAAABwAAACMAAAA2fH//4UAAAAARQ4QhgJDDQYCfAwHCAAAHAAAAKwAAAA+8v//QgEAAABFDhCGAkMNBgM5AQwHCAAcAAAAzAAAAGDz//85AQAAAEUOEIYCQw0GAzABDAcIABwAAADsAAAAefT///8CAAAARQ4QhgJDDQYD9gIMBwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwBMAAAAAAACAEwAAAAAAAAEAAAAAAAAApAAAAAAAAAAMAAAAAAAAAAAQAAAAAAAADQAAAAAAAADIGQAAAAAAABkAAAAAAAAAGD0AAAAAAAAbAAAAAAAAAAgAAAAAAAAAGgAAAAAAAAAgPQAAAAAAABwAAAAAAAAACAAAAAAAAAD1/v9vAAAAALADAAAAAAAABQAAAAAAAAB4BgAAAAAAAAYAAAAAAAAA2AMAAAAAAAAKAAAAAAAAABQBAAAAAAAACwAAAAAAAAAYAAAAAAAAABUAAAAAAAAAAAAAAAAAAAADAAAAAAAAABg/AAAAAAAAAgAAAAAAAAD4AQAAAAAAABQAAAAAAAAABwAAAAAAAAAXAAAAAAAAAPgIAAAAAAAABwAAAAAAAAAICAAAAAAAAAgAAAAAAAAA8AAAAAAAAAAJAAAAAAAAABgAAAAAAAAAHgAAAAAAAAAIAAAAAAAAAPv//28AAAAAAQAACAAAAAD+//9vAAAAAMgHAAAAAAAA////bwAAAAABAAAAAAAAAPD//28AAAAAjAcAAAAAAAD5//9vAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEAAAAAAAAEAQAAAAAAAAUBAAAAAAAABgEAAAAAAAAHAQAAAAAAAAgBAAAAAAAACQEAAAAAAAAKAQAAAAAAAAsBAAAAAAAADAEAAAAAAAANAQAAAAAAAA4BAAAAAAAADwEAAAAAAAAAARAAAAAAAAEBEAAAAAAAAgEQAAAAAAADARAAAAAAAAQBEAAAAAAABQEQAAAAAAAGARAAAAAAAAcBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAP////8AAAAACCAAAAAAAABHQ0M6IChVYnVudHUgMTMuMy4wLTZ1YnVudHUyfjI0LjA0KSAxMy4zLjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAJAAAAAQAEAIwDAAAAAAAAIAAAAAAAAAATAAAABADx/wAAAAAAAAAAAAAAAAAAAAAeAAAAAgAQABATAAAAAAAAAAAAAAAAAAAgAAAAAgAQAEATAAAAAAAAAAAAAAAAAAAzAAAAAgAQAIATAAAAAAAAAAAAAAAAAABJAAAAAQAaAChAAAAAAAAAAQAAAAAAAABVAAAAAQAWACA9AAAAAAAAAAAAAAAAAAB8AAAAAgAQAMATAAAAAAAAAAAAAAAAAACIAAAAAQAVABg9AAAAAAAAAAAAAAAAAACnAAAABADx/wAAAAAAAAAAAAAAAAAAAAATAAAABADx/wAAAAAAAAAAAAAAAAAAAAC3AAAAAQAUAGgiAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAADFAAAAAQAXACg9AAAAAAAAAAAAAAAAAADOAAAAAAATABQhAAAAAAAAAAAAAAAAAADhAAAAAQAYABg/AAAAAAAAAAAAAAAAAAD3AAAAEgAAAAAAAAAAAAAAAAAAAAAAAAAUAQAAIAAAAAAAAAAAAAAAAAAAAAAAAAAwAQAAEQAaACBAAAAAAAAACAAAAAAAAADkAQAAIAAZAABAAAAAAAAAAAAAAAAAAABDAQAAEAAZACBAAAAAAAAAAAAAAAAAAABKAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABdAQAAEgIRAMgZAAAAAAAAAAAAAAAAAABjAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAB+AQAAEQAaACxAAAAAAAAABAAAAAAAAACKAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACdAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADeAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABLAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACuAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAC/AQAAEgAAAAAAAAAAAAAAAAAAAAAAAADQAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADiAQAAEAAZAABAAAAAAAAAAAAAAAAAAADvAQAAEQAZABBAAAAAAAAABAAAAAAAAAD9AQAAIAAAAAAAAAAAAAAAAAAAAAAAAAAMAgAAEQIZAAhAAAAAAAAAAAAAAAAAAAAZAgAAEQASAAAgAAAAAAAABAAAAAAAAAAoAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAA5AgAAEgAAAAAAAAAAAAAAAAAAAAAAAABMAgAAEgAQAMkTAAAAAAAAhQAAAAAAAABXAgAAEAAaADBAAAAAAAAAAAAAAAAAAADoAQAAEgAQAOASAAAAAAAAJgAAAAAAAABcAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABvAgAAEAAaACBAAAAAAAAAAAAAAAAAAAB7AgAAEgAQAMkWAAAAAAAA/wIAAAAAAACAAgAAEgAQAJAVAAAAAAAAOQEAAAAAAACIAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABeAgAAEgAAAAAAAAAAAAAAAAAAAAAAAACcAgAAEgAAAAAAAAAAAAAAAAAAAAAAAACvAgAAEQAZABhAAAAAAAAACAAAAAAAAAC5AgAAEgAAAAAAAAAAAAAAAAAAAAAAAADMAgAAEgAAAAAAAAAAAAAAAAAAAAAAAADdAgAAEgAAAAAAAAAAAAAAAAAAAAAAAADxAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAACAwAAEQIZACBAAAAAAAAAAAAAAAAAAAAOAwAAIAAAAAAAAAAAAAAAAAAAAAAAAAAoAwAAIgAAAAAAAAAAAAAAAAAAAAAAAABDAwAAEgIMAAAQAAAAAAAAAAAAAAAAAABJAwAAEgAAAAAAAAAAAAAAAAAAAAAAAABaAwAAEgAAAAAAAAAAAAAAAAAAAAAAAABtAwAAEgAQAE4UAAAAAAAAQgEAAAAAAAAAU2NydDEubwBfX2FiaV90YWcAY3J0c3R1ZmYuYwBkZXJlZ2lzdGVyX3RtX2Nsb25lcwBfX2RvX2dsb2JhbF9kdG9yc19hdXgAY29tcGxldGVkLjAAX19kb19nbG9iYWxfZHRvcnNfYXV4X2ZpbmlfYXJyYXlfZW50cnkAZnJhbWVfZHVtbXkAX19mcmFtZV9kdW1teV9pbml0X2FycmF5X2VudHJ5AGRlYnVnZ2luZ19iaW4uYwBfX0ZSQU1FX0VORF9fAF9EWU5BTUlDAF9fR05VX0VIX0ZSQU1FX0hEUgBfR0xPQkFMX09GRlNFVF9UQUJMRV8AX19saWJjX3N0YXJ0X21haW5AR0xJQkNfMi4zNABfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAc3Rkb3V0QEdMSUJDXzIuMi41AF9lZGF0YQBmY2xvc2VAR0xJQkNfMi4yLjUAX2ZpbmkAX19zdGFja19jaGtfZmFpbEBHTElCQ18yLjQAcGlkX2NvdW50ZXIAc2V0YnVmQEdMSUJDXzIuMi41AGR1cDJAR0xJQkNfMi4yLjUAcGlwZUBHTElCQ18yLjIuNQByZWFkQEdMSUJDXzIuMi41AGZnZXRzQEdMSUJDXzIuMi41AF9fZGF0YV9zdGFydABnZGJzZXJ2ZXJfcGlkAF9fZ21vbl9zdGFydF9fAF9fZHNvX2hhbmRsZQBfSU9fc3RkaW5fdXNlZABraWxsQEdMSUJDXzIuMi41AG1hbGxvY0BHTElCQ18yLjIuNQByZWFkX3VudGlsAF9lbmQAZmRvcGVuQEdMSUJDXzIuMi41AF9fYnNzX3N0YXJ0AG1haW4AcnVuX2dkYgB3YWl0cGlkQEdMSUJDXzIuMi41AHBlcnJvckBHTElCQ18yLjIuNQBzZXBhcmF0b3IAZXhlY3ZwQEdMSUJDXzIuMi41AGF0b2lAR0xJQkNfMi4yLjUAc3ByaW50ZkBHTElCQ18yLjIuNQBleGl0QEdMSUJDXzIuMi41AF9fVE1DX0VORF9fAF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19jeGFfZmluYWxpemVAR0xJQkNfMi4yLjUAX2luaXQAZm9ya0BHTElCQ18yLjIuNQBzdHJzdHJAR0xJQkNfMi4yLjUAZmluZF9tYXhfcGlkAAAuc3ltdGFiAC5zdHJ0YWIALnNoc3RydGFiAC5pbnRlcnAALm5vdGUuZ251LnByb3BlcnR5AC5ub3RlLmdudS5idWlsZC1pZAAubm90ZS5BQkktdGFnAC5nbnUuaGFzaAAuZHluc3ltAC5keW5zdHIALmdudS52ZXJzaW9uAC5nbnUudmVyc2lvbl9yAC5yZWxhLmR5bgAucmVsYS5wbHQALmluaXQALnBsdC5nb3QALnBsdC5zZWMALnRleHQALmZpbmkALnJvZGF0YQAuZWhfZnJhbWVfaGRyAC5laF9mcmFtZQAuaW5pdF9hcnJheQAuZmluaV9hcnJheQAuZHluYW1pYwAuZGF0YQAuYnNzAC5jb21tZW50AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAAAEAAAACAAAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACMAAAAHAAAAAgAAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAA2AAAABwAAAAIAAAAAAAAAaAMAAAAAAABoAwAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAASQAAAAcAAAACAAAAAAAAAIwDAAAAAAAAjAMAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAFcAAAD2//9vAgAAAAAAAACwAwAAAAAAALADAAAAAAAAKAAAAAAAAAAGAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABhAAAACwAAAAIAAAAAAAAA2AMAAAAAAADYAwAAAAAAAKACAAAAAAAABwAAAAEAAAAIAAAAAAAAABgAAAAAAAAAaQAAAAMAAAACAAAAAAAAAHgGAAAAAAAAeAYAAAAAAAAUAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHEAAAD///9vAgAAAAAAAACMBwAAAAAAAIwHAAAAAAAAOAAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAB+AAAA/v//bwIAAAAAAAAAyAcAAAAAAADIBwAAAAAAAEAAAAAAAAAABwAAAAEAAAAIAAAAAAAAAAAAAAAAAAAAjQAAAAQAAAACAAAAAAAAAAgIAAAAAAAACAgAAAAAAADwAAAAAAAAAAYAAAAAAAAACAAAAAAAAAAYAAAAAAAAAJcAAAAEAAAAQgAAAAAAAAD4CAAAAAAAAPgIAAAAAAAA+AEAAAAAAAAGAAAAGAAAAAgAAAAAAAAAGAAAAAAAAAChAAAAAQAAAAYAAAAAAAAAABAAAAAAAAAAEAAAAAAAABsAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAnAAAAAEAAAAGAAAAAAAAACAQAAAAAAAAIBAAAAAAAABgAQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAKcAAAABAAAABgAAAAAAAACAEQAAAAAAAIARAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACwAAAAAQAAAAYAAAAAAAAAkBEAAAAAAACQEQAAAAAAAFABAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAuQAAAAEAAAAGAAAAAAAAAOASAAAAAAAA4BIAAAAAAADoBgAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAL8AAAABAAAABgAAAAAAAADIGQAAAAAAAMgZAAAAAAAADQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADFAAAAAQAAAAIAAAAAAAAAACAAAAAAAAAAIAAAAAAAABMBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAzQAAAAEAAAACAAAAAAAAABQhAAAAAAAAFCEAAAAAAABMAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAANsAAAABAAAAAgAAAAAAAABgIQAAAAAAAGAhAAAAAAAADAEAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADlAAAADgAAAAMAAAAAAAAAGD0AAAAAAAAYLQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA8QAAAA8AAAADAAAAAAAAACA9AAAAAAAAIC0AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAP0AAAAGAAAAAwAAAAAAAAAoPQAAAAAAACgtAAAAAAAA8AEAAAAAAAAHAAAAAAAAAAgAAAAAAAAAEAAAAAAAAACrAAAAAQAAAAMAAAAAAAAAGD8AAAAAAAAYLwAAAAAAAOgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABgEAAAEAAAADAAAAAAAAAABAAAAAAAAAADAAAAAAAAAgAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwBAAAIAAAAAwAAAAAAAAAgQAAAAAAAACAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAARAQAAAQAAADAAAAAAAAAAAAAAAAAAAAAgMAAAAAAAACsAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAUDAAAAAAAADoBQAAAAAAAB0AAAASAAAACAAAAAAAAAAYAAAAAAAAAAkAAAADAAAAAAAAAAAAAAAAAAAAAAAAADg2AAAAAAAAegMAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAAwAAAAAAAAAAAAAAAAAAAAAAAACyOQAAAAAAABoBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"
DOCKER_SETUP = f'''

# DOCKER SETUP BY docker-debugger
COPY {BINARY_NAME} /{BINARY_NAME}
RUN apt update
RUN apt install -y gdbserver

'''

# Routine to restore the backup if -r (--restore-backup) argument is passed
def restore():
    restored = False
    try:
        f1 = open("Dockerfile.bak", "r")
        f2 = open("docker-compose.bak", "r")
        dockerfile = f1.read()
        docker_compose = f2.read()
        f1.close()
        f2.close()
        f = open("Dockerfile", "w")
        f.write(dockerfile)
        f.close()
        f = open("docker-compose.yml", "w")
        f.write(docker_compose)
        f.close()
        print("Backup successfully restored")
        restored = True
        exit(0)
    except:
        if restored == True:
            exit()
        print("Backup restore failed")
        exit(1)

# Parse command line arguments
def arg_parser():
    global DOCKER_PATH, GDBSERVER_PORT, CHALLENGE_PATH
    if len(sys.argv) < 2:
        print(HELP)
        exit(1)
    positional_arguments = 0
    i = 1
    while i < len(sys.argv):
        arg = sys.argv[i]

        if arg == "-h" or arg == "--help":
            print(HELP)
            exit()

        elif arg == "-r" or arg == "--restore-backup":
            restore()
            exit()

        elif arg == "-u" or arg == "--docker-path":
            if (i + 1) >= len(sys.argv):
                print(HELP)
                exit(1)
            path = sys.argv[i + 1]
            if os.path.exists(path):
                DOCKER_PATH = path
            else:
                print("Invalid path!")
                exit(1)
            i = i + 1
        
        elif arg == "-p" or arg == "--port":
            if (i + 1) >= len(sys.argv):
                print(HELP)
                exit(1)
            port = sys.argv[i + 1]
            try:
                port = int(port)
            except:
                print("Port must be an integer!")
                exit(1)
            if port <= 0 or port > 65535:
                print("Port must be in range 1-65535")
                exit(1)
            GDBSERVER_PORT = port
            i = i + 1
        
        else:
            if positional_arguments >= POSITIONAL_ARGUMENTS:
                print("To much arguments!")
                print(HELP)
                exit(1)
            if positional_arguments == 0:
                CHALLENGE_PATH = arg
            positional_arguments = positional_arguments + 1
        i = i + 1


# Parse the socat command runned in the Dockerfile
def docker_cmd_arg_extract(command):
    # Put all the command in one line to parse it easily
    inline_command = command.split("\\")
    for i in range(len(inline_command)):
        inline_command[i] = inline_command[i].strip() + " "
    inline_command = "".join(inline_command)

    # Construct a list containing the arguments
    command_args = inline_command[len("CMD socat "):]
    args_list = ["socat"]
    new_arg = ""
    in_string = False
    for car in command_args:
        if car == " " and in_string == False:
            args_list.append(new_arg)
            new_arg = ""
            continue
        elif car == '"':
            in_string = not in_string
        new_arg = new_arg + car
    if new_arg != "":
        args_list.append(new_arg)
    return args_list

# Add the socat verbose option (-d -d) to the arguments
def add_verbose(arguments):
    new_args = []
    new_args.append(arguments[0])
    new_args.append("-d")
    new_args.append("-d")
    new_args = new_args + arguments[1:]
    return new_args

# Add the option field with value value to the docker-compose passed as a string in compose
def add_compose_option(compose ,field, value):
    field_indentation = ""
    value_identation = ""
    is_value = False
    for line in compose.split("\n"):
        if is_value == True:
            value_identation = line[:line.find("-")]
            break
        if "ports:" in line:
            field_indentation = line[:line.find("ports:")]
            is_value = True

    new_compose = compose[:compose.find(f"{field_indentation}ports:")] +\
                  f"{field_indentation}{field}:\n{value_identation}- {value}\n" +\
                  compose[compose.find(f"{field_indentation}ports:"):]
    return new_compose
    

def main():
    arg_parser()

    # Check for Dockerfile
    dockerfile_path = os.path.join(DOCKER_PATH, "Dockerfile")
    compose_yml_path = os.path.join(DOCKER_PATH, "docker-compose.yml")
    compose_yaml_path = os.path.join(DOCKER_PATH, "docker-compose.yaml")

    if not os.path.isfile(dockerfile_path):
        print("Dockerfile not found in the specified path.")
        exit(1)

    # Rename docker-compose.yaml to docker-compose.yml
    if os.path.isfile(compose_yaml_path) and not os.path.isfile(compose_yml_path):
        os.rename(compose_yaml_path, compose_yml_path)

    if not os.path.isfile(compose_yml_path):
        print("docker-compose.yml not found in the specified path.")
        exit(1)

    # Open Dockerfile
    f = open(dockerfile_path, "r")
    dockerfile = f.read()
    f.close()

    # Check if Dockerfile has been patched yet
    if "# DOCKER SETUP BY docker-debugger" in dockerfile:
        print("Project alredy patched, restore the backup before using docker-debugger again")
        exit(1)

    # Check if Dockerfile use socat
    command = dockerfile[dockerfile.find("CMD "):]
    if not "socat" in command:
        print("This docker doesn't use socat...")
        exit(1)
    
    # Parse the command executed by Dockerfile and add verbose option to the socat command
    args_list = docker_cmd_arg_extract(command)
    args_list = add_verbose(args_list)

    # Write arguments to pass them as arguments in the new Dockerfile command
    cli_args = ""
    for elem in args_list:
        cli_args = cli_args + " " + elem

    # Generating debugging_bin
    f = open(f"{BINARY_NAME}", "wb")
    f.write(base64.b64decode(BINARY))
    f.close()
    os.chmod(f"{BINARY_NAME}", 0o755)


    # Write a backup of Dockerfile in Dockerfile.bak
    f = open(dockerfile_path + ".bak", "w")
    f.write(dockerfile)
    f.close()

    # patch Dockerfile
    patched_command = f"CMD /{BINARY_NAME} {CHALLENGE_PATH} {GDBSERVER_PORT}{cli_args}"
    nuovo = dockerfile.split("CMD")
    nuovo[0] = nuovo[0] + DOCKER_SETUP + "# OLD EXECUTION COMMAND\n" + "# CMD"
    nuovo[1] =  nuovo[1].replace("\n", "\n#") + "\n\n" + patched_command
    nuovo = "".join(nuovo)
    f = open("Dockerfile", "w")
    f.write(nuovo)
    f.close()

    # Write backup for docker-compose.yml in docker-compose.bak
    f = open(compose_yml_path, "r")
    docker_compose = f.read()
    f.close()
    f = open(compose_yml_path.replace("yml", "bak"), "w")
    f.write(docker_compose)
    f.close()

    # Patch docker-compose.yml
    nuovo = docker_compose.split("ports:")
    identation = nuovo[1].split("\n")[1]
    identation = identation[:identation.find("-")]
    nuovo[0] = nuovo[0] + "ports:\n"
    nuovo[1] = (identation + f"- {GDBSERVER_PORT}:{GDBSERVER_PORT}") + nuovo[1]
    nuovo = "".join(nuovo)
    nuovo = add_compose_option(nuovo, "cap_add", "SYS_PTRACE")
    nuovo = add_compose_option(nuovo, "security_opt", "seccomp=unconfined")
    f = open(compose_yml_path, "w")
    f.write(nuovo)
    f.close()

if __name__ == "__main__":
    main()