#!/usr/bin/python3

import sys
import os
import base64

POSITIONAL_ARGUMENTS = 1
GDBSERVER_PORT = 1234
DOCKER_PATH = "./"
HELP = '''
Usage: docker-debugger /path/to/challenge/binary/in/docker


OPTIONS:
    -r --restore-backup: restore the backups (Usable only if there are Dockerfile.bak and dokcer-compose.bak files)
    -u --docker-path: path to the Dokcerfile and docker-compose.yml (default: ./)
    -p --port: port where gdbserver will listen (default: 1234)
    -h --help: print this message
'''
CHALLENGE_PATH = ""
BINARY_NAME = "debugging_bin"
BINARY = b"f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAwBIAAAAAAABAAAAAAAAAAKg6AAAAAAAAAAAAAEAAOAANAEAAHwAeAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgKAAAAAAAAuAoAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAPQkAAAAAAAA9CQAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAABcAgAAAAAAAFwCAAAAAAAAABAAAAAAAAABAAAABgAAACAtAAAAAAAAID0AAAAAAAAgPQAAAAAAAAADAAAAAAAAEAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAAMC0AAAAAAAAwPQAAAAAAADA9AAAAAAAA8AEAAAAAAADwAQAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAAAIQAAAAAAAAAhAAAAAAAAACEAAAAAAABMAAAAAAAAAEwAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAAIC0AAAAAAAAgPQAAAAAAACA9AAAAAAAA4AIAAAAAAADgAgAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAAAQAAAAAAAAAEAAAAFAAAAAMAAABHTlUAS+/VyGl0AacwQZ8t7WyhbnmA6WYEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAACAAAAGQAAAAEAAAAGAAAAAACBAAABEAAZAAAAAAAAACgdjBzRZc5tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAygAAACAAAAAAAAAAAAAAAAAAAAAAAAAAiwAAABIAAAAAAAAAAAAAAAAAAAAAAAAADgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAJAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAPAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAfwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAjAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAmgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA5gAAACAAAAAAAAAAAAAAAAAAAAAAAAAAhgAAABIAAAAAAAAAAAAAAAAAAAAAAAAATwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAaAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAkgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAagAAABIAAAAAAAAAAAAAAAAAAAAAAAAABwAAABIAAAAAAAAAAAAAAAAAAAAAAAAASAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAfgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAHwAAABIAAAAAAAAAAAAAAAAAAAAAAAAA9QAAACAAAAAAAAAAAAAAAAAAAAAAAAAAKwAAABIAAAAAAAAAAAAAAAAAAAAAAAAANQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAQQAAABEAGgAgQAAAAAAAAAgAAAAAAAAAbwAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAGZnZXRzAHBlcnJvcgBfX3N0YWNrX2Noa19mYWlsAGV4aXQAc2V0YnVmAGZvcmsAcmVhZABzdHJzdHIAZHVwMgBzdGRvdXQAZXhlY3ZwAG1hbGxvYwBfX2xpYmNfc3RhcnRfbWFpbgBmZG9wZW4AX19jeGFfZmluYWxpemUAc3ByaW50ZgBraWxsAGZjbG9zZQB3YWl0cGlkAHBpcGUAbGliYy5zby42AEdMSUJDXzIuNABHTElCQ18yLjIuNQBHTElCQ18yLjM0AF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfX2dtb25fc3RhcnRfXwBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAAAAAAIAAQADAAQAAwADAAMAAwADAAMAAwABAAMAAwADAAMAAwADAAMAAwADAAEAAwADAAMAAwAAAAEAAwCfAAAAEAAAAAAAAAAUaWkNAAAEAKkAAAAQAAAAdRppCQAAAwCzAAAAEAAAALSRlgYAAAIAvwAAAAAAAAAgPQAAAAAAAAgAAAAAAAAAoBMAAAAAAAAoPQAAAAAAAAgAAAAAAAAAYBMAAAAAAAAIQAAAAAAAAAgAAAAAAAAACEAAAAAAAAAYQAAAAAAAAAgAAAAAAAAACCAAAAAAAADYPwAAAAAAAAYAAAABAAAAAAAAAAAAAADgPwAAAAAAAAYAAAACAAAAAAAAAAAAAADoPwAAAAAAAAYAAAAMAAAAAAAAAAAAAADwPwAAAAAAAAYAAAAWAAAAAAAAAAAAAAD4PwAAAAAAAAYAAAAaAAAAAAAAAAAAAAAgQAAAAAAAAAUAAAAZAAAAAAAAAAAAAAA4PwAAAAAAAAcAAAADAAAAAAAAAAAAAABAPwAAAAAAAAcAAAAEAAAAAAAAAAAAAABIPwAAAAAAAAcAAAAFAAAAAAAAAAAAAABQPwAAAAAAAAcAAAAGAAAAAAAAAAAAAABYPwAAAAAAAAcAAAAHAAAAAAAAAAAAAABgPwAAAAAAAAcAAAAIAAAAAAAAAAAAAABoPwAAAAAAAAcAAAAJAAAAAAAAAAAAAABwPwAAAAAAAAcAAAAKAAAAAAAAAAAAAAB4PwAAAAAAAAcAAAALAAAAAAAAAAAAAACAPwAAAAAAAAcAAAANAAAAAAAAAAAAAACIPwAAAAAAAAcAAAAOAAAAAAAAAAAAAACQPwAAAAAAAAcAAAAPAAAAAAAAAAAAAACYPwAAAAAAAAcAAAAQAAAAAAAAAAAAAACgPwAAAAAAAAcAAAARAAAAAAAAAAAAAACoPwAAAAAAAAcAAAASAAAAAAAAAAAAAACwPwAAAAAAAAcAAAATAAAAAAAAAAAAAAC4PwAAAAAAAAcAAAAUAAAAAAAAAAAAAADAPwAAAAAAAAcAAAAVAAAAAAAAAAAAAADIPwAAAAAAAAcAAAAXAAAAAAAAAAAAAADQPwAAAAAAAAcAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wISIsF2S8AAEiFwHQC/9BIg8QIwwAAAAAA/zUCLwAA/yUELwAADx9AAPMPHvpoAAAAAOni////ZpDzDx76aAEAAADp0v///2aQ8w8e+mgCAAAA6cL///9mkPMPHvpoAwAAAOmy////ZpDzDx76aAQAAADpov///2aQ8w8e+mgFAAAA6ZL///9mkPMPHvpoBgAAAOmC////ZpDzDx76aAcAAADpcv///2aQ8w8e+mgIAAAA6WL///9mkPMPHvpoCQAAAOlS////ZpDzDx76aAoAAADpQv///2aQ8w8e+mgLAAAA6TL///9mkPMPHvpoDAAAAOki////ZpDzDx76aA0AAADpEv///2aQ8w8e+mgOAAAA6QL///9mkPMPHvpoDwAAAOny/v//ZpDzDx76aBAAAADp4v7//2aQ8w8e+mgRAAAA6dL+//9mkPMPHvpoEgAAAOnC/v//ZpDzDx76aBMAAADpsv7//2aQ8w8e+v8lfi4AAGYPH0QAAPMPHvr/Ja4tAABmDx9EAADzDx76/yWmLQAAZg8fRAAA8w8e+v8lni0AAGYPH0QAAPMPHvr/JZYtAABmDx9EAADzDx76/yWOLQAAZg8fRAAA8w8e+v8lhi0AAGYPH0QAAPMPHvr/JX4tAABmDx9EAADzDx76/yV2LQAAZg8fRAAA8w8e+v8lbi0AAGYPH0QAAPMPHvr/JWYtAABmDx9EAADzDx76/yVeLQAAZg8fRAAA8w8e+v8lVi0AAGYPH0QAAPMPHvr/JU4tAABmDx9EAADzDx76/yVGLQAAZg8fRAAA8w8e+v8lPi0AAGYPH0QAAPMPHvr/JTYtAABmDx9EAADzDx76/yUuLQAAZg8fRAAA8w8e+v8lJi0AAGYPH0QAAPMPHvr/JR4tAABmDx9EAADzDx76/yUWLQAAZg8fRAAA8w8e+jHtSYnRXkiJ4kiD5PBQVEUxwDHJSI09ogMAAP8V8ywAAPRmLg8fhAAAAAAASI09KS0AAEiNBSItAABIOfh0FUiLBdYsAABIhcB0Cf/gDx+AAAAAAMMPH4AAAAAASI09+SwAAEiNNfIsAABIKf5IifBIwe4/SMH4A0gBxkjR/nQUSIsFpSwAAEiFwHQI/+BmDx9EAADDDx+AAAAAAPMPHvqAPb0sAAAAdStVSIM9giwAAABIieV0DEiLPYYsAADo6f3//+hk////xgWVLAAAAV3DDx8Aww8fgAAAAADzDx766Xf////zDx76VUiJ5UiD7CCJfexIiXXgidCIRehkSIsEJSgAAABIiUX4McDHRfQAAAAASI1N84tF7LoBAAAASInOicfoA/7//0iFwHQii0X0SGPQSItF4EgBwg+2RfOIAoNF9AEPtkXzOEXodcXrAZCLRfRIi1X4ZEgrFCUoAAAAdAXoZP3//8nD8w8e+lVIieVIgexwAQAAib2c/v//SIm1kP7//2RIiwQlKAAAAEiJRfgxwMeFoP7///////+LhZz+//+JhaT+///p0AAAAIuVpP7//0iNhbD+//9IjQ3WCwAASInOSInHuAAAAADo6P3//0iNhbD+//++AAAAAEiJx7gAAAAA6J/9//+Jhaj+//+Dvaj+//8AeHxIjY3w/v//i4Wo/v//ugAAAABIic6Jx+jN/v//iYWs/v//i4Wo/v//icfo4fz//4O9rP7//wB+RUiLlZD+//9IjYXw/v//SInWSInH6J/9//9IicJIjYXw/v//SDnCdR2LhaT+//87haD+//9+D4uFpP7//4mFoP7//+sBkIOFpP7//wGBvaT+////fwAAD44g////i4Wg/v//SItV+GRIKxQlKAAAAHQF6CL8///Jw/MPHvpVSInlSIPsUIl9vGRIiwQlKAAAAEiJRfgxwIsFfCoAAIXAfjKLBXIqAAC+CQAAAInH6Gb8//+FwHUciwVcKgAAicZIjQWyCgAASInHuAAAAADo9vv//+jR/P//iUXMg33MAHVtSI0FqgoAAEiJRdBIjQWpCgAASIlF2EiNBaQKAABIiUXgvxAAAADoHfz//0iJRehIi0Xoi1W8SI0NjQoAAEiJzkiJx7gAAAAA6Fv8//9Ix0XwAAAAAEiNRdBIicZIjQVOCgAASInH6C38///rJYtFzIkFwikAAIsFvCkAAInGSI0FSAoAAEiJx7gAAAAA6Fb7//+QSItF+GRIKwQlKAAAAHQF6BH7///Jw/MPHvpVSInlSIHsUAQAAIm9vPv//0iJtbD7//9kSIsEJSgAAABIiUX4McBIiwVtKQAAvgAAAABIicfo4Pr//4O9vPv//wF/GUiNBfEJAABIicfoiPv//78BAAAA6K77//9Ii4Ww+///SItACEiJhdD7//+Lhbz7//+D6AFImEjB4ANIicfoFfv//0iJhdj7///HhcT7//8CAAAA60KLhcT7//9ImEiNFMUAAAAASIuFsPv//0gB0IuVxPv//0hj0kjB4gNIjUrwSIuV2Pv//0gBykiLAEiJAoOFxPv//wGLhcT7//87hbz7//98sIuFvPv//0iYSMHgA0iNUPBIi4XY+///SAHQSMcAAAAAAEiNhej7//9IicfoQvr//+j9+v//iYXI+///g73I+///AHVzi4Xo+///icfoEfr//4uF7Pv//74BAAAAicfo3/n//4uF7Pv//74CAAAAicfozfn//4uF7Pv//4nH6OD5//9Ii4XY+///SIsASIuV2Pv//0iJ1kiJx+hk+v//SI0FxAgAAEiJx+hF+v//vwEAAADoa/r//4uF7Pv//4nH6J75//+Lhej7//9IjRWxCAAASInWicfo5/n//0iJheD7//9Ig73g+///AHUZSI0FkQgAAEiJx+j3+f//vwEAAADoHfr//0iLheD7//++AAAAAEiJx+gZ+f//60SLBZ0nAABIi5XQ+///SInWicfojvv//4mFzPv//4sFgCcAADmFzPv//34Zi4XM+///iQVsJwAAi4XM+///icfoo/z//0iLleD7//9IjYXw+///vgAEAABIicfoGPn//0iFwHWcSIuF4Pv//0iJx+iE+P//i4XI+///ugAAAAC+AAAAAInH6C35//+4AAAAAEiLVfhkSCsUJSgAAAB0Behk+P//ycMAAPMPHvpIg+wISIPECMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAAAAAAAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoAL3Byb2MvJWQvY21kbGluZQBLaWxsZWQgZ2Ric2VydmVyIChQSUQ9JWQpAGdkYnNlcnZlcgA6MTIzNAAtLWF0dGFjaAAlZABTdGFydGluZyBnZGJzZXJ2ZXIgKFBJRD0lZCkATm90IGVub3VnaCBhcmd1bWVudHMhAEJpbmFyeSBleGVjdXRpb24gZmFpbGVkIQByAGZkb3BlbiBmYWlsZWQAARsDO0wAAAAIAAAAIO///4AAAABw8P//qAAAAIDw///AAAAAwPH//2gAAACp8v//2AAAAC7z///4AAAAcPT//xgBAACB9f//OAEAAAAAAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAUAAAAHAAAAFDx//8mAAAAAEQHEAAAAAAkAAAANAAAAJju//9QAQAAAA4QRg4YSg8LdwiAAD8aOSozJCIAAAAAFAAAAFwAAADA7///EAAAAAAAAAAAAAAAFAAAAHQAAAC47///QAEAAAAAAAAAAAAAHAAAAIwAAADJ8f//hQAAAABFDhCGAkMNBgJ8DAcIAAAcAAAArAAAAC7y//9CAQAAAEUOEIYCQw0GAzkBDAcIABwAAADMAAAAUPP//xEBAAAARQ4QhgJDDQYDCAEMBwgAHAAAAOwAAABB9P//rQIAAABFDhCGAkMNBgOkAgwHCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgEwAAAAAAAGATAAAAAAAAAQAAAAAAAACfAAAAAAAAAAwAAAAAAAAAABAAAAAAAAANAAAAAAAAADAZAAAAAAAAGQAAAAAAAAAgPQAAAAAAABsAAAAAAAAACAAAAAAAAAAaAAAAAAAAACg9AAAAAAAAHAAAAAAAAAAIAAAAAAAAAPX+/28AAAAAsAMAAAAAAAAFAAAAAAAAAGAGAAAAAAAABgAAAAAAAADYAwAAAAAAAAoAAAAAAAAADwEAAAAAAAALAAAAAAAAABgAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAID8AAAAAAAACAAAAAAAAAOABAAAAAAAAFAAAAAAAAAAHAAAAAAAAABcAAAAAAAAA2AgAAAAAAAAHAAAAAAAAAOgHAAAAAAAACAAAAAAAAADwAAAAAAAAAAkAAAAAAAAAGAAAAAAAAAAeAAAAAAAAAAgAAAAAAAAA+///bwAAAAABAAAIAAAAAP7//28AAAAAqAcAAAAAAAD///9vAAAAAAEAAAAAAAAA8P//bwAAAABwBwAAAAAAAPn//28AAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA9AAAAAAAAAAAAAAAAAAAAAAAAAAAAADAQAAAAAAAAQBAAAAAAAABQEAAAAAAAAGAQAAAAAAAAcBAAAAAAAACAEAAAAAAAAJAQAAAAAAAAoBAAAAAAAACwEAAAAAAAAMAQAAAAAAAA0BAAAAAAAADgEAAAAAAAAPAQAAAAAAAAABEAAAAAAAAQEQAAAAAAACARAAAAAAAAMBEAAAAAAABAEQAAAAAAAFARAAAAAAAAYBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAP////8AAAAACCAAAAAAAABHQ0M6IChVYnVudHUgMTMuMy4wLTZ1YnVudHUyfjI0LjA0KSAxMy4zLjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAJAAAAAQAEAIwDAAAAAAAAIAAAAAAAAAATAAAABADx/wAAAAAAAAAAAAAAAAAAAAAeAAAAAgAQAPASAAAAAAAAAAAAAAAAAAAgAAAAAgAQACATAAAAAAAAAAAAAAAAAAAzAAAAAgAQAGATAAAAAAAAAAAAAAAAAABJAAAAAQAaAChAAAAAAAAAAQAAAAAAAABVAAAAAQAWACg9AAAAAAAAAAAAAAAAAAB8AAAAAgAQAKATAAAAAAAAAAAAAAAAAACIAAAAAQAVACA9AAAAAAAAAAAAAAAAAACnAAAABADx/wAAAAAAAAAAAAAAAAAAAAATAAAABADx/wAAAAAAAAAAAAAAAAAAAAC3AAAAAQAUAFgiAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAADFAAAAAQAXADA9AAAAAAAAAAAAAAAAAADOAAAAAAATAAAhAAAAAAAAAAAAAAAAAADhAAAAAQAYACA/AAAAAAAAAAAAAAAAAAD3AAAAEgAAAAAAAAAAAAAAAAAAAAAAAAAUAQAAIAAAAAAAAAAAAAAAAAAAAAAAAAAwAQAAEQAaACBAAAAAAAAACAAAAAAAAADkAQAAIAAZAABAAAAAAAAAAAAAAAAAAABDAQAAEAAZACBAAAAAAAAAAAAAAAAAAABKAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABdAQAAEgIRADAZAAAAAAAAAAAAAAAAAABjAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAB+AQAAEQAaACxAAAAAAAAABAAAAAAAAACKAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACdAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADNAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABLAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACuAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAC/AQAAEgAAAAAAAAAAAAAAAAAAAAAAAADQAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADiAQAAEAAZAABAAAAAAAAAAAAAAAAAAADvAQAAEQAZABBAAAAAAAAABAAAAAAAAAD9AQAAIAAAAAAAAAAAAAAAAAAAAAAAAAAMAgAAEQIZAAhAAAAAAAAAAAAAAAAAAAAZAgAAEQASAAAgAAAAAAAABAAAAAAAAAAoAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAA5AgAAEgAAAAAAAAAAAAAAAAAAAAAAAABMAgAAEgAQAKkTAAAAAAAAhQAAAAAAAABXAgAAEAAaADBAAAAAAAAAAAAAAAAAAADoAQAAEgAQAMASAAAAAAAAJgAAAAAAAABcAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABvAgAAEAAaACBAAAAAAAAAAAAAAAAAAAB7AgAAEgAQAIEWAAAAAAAArQIAAAAAAACAAgAAEgAQAHAVAAAAAAAAEQEAAAAAAACIAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABeAgAAEgAAAAAAAAAAAAAAAAAAAAAAAACcAgAAEgAAAAAAAAAAAAAAAAAAAAAAAACvAgAAEQAZABhAAAAAAAAACAAAAAAAAAC5AgAAEgAAAAAAAAAAAAAAAAAAAAAAAADMAgAAEgAAAAAAAAAAAAAAAAAAAAAAAADgAgAAEgAAAAAAAAAAAAAAAAAAAAAAAADxAgAAEQIZACBAAAAAAAAAAAAAAAAAAAD9AgAAIAAAAAAAAAAAAAAAAAAAAAAAAAAXAwAAIgAAAAAAAAAAAAAAAAAAAAAAAAAyAwAAEgIMAAAQAAAAAAAAAAAAAAAAAAA4AwAAEgAAAAAAAAAAAAAAAAAAAAAAAABJAwAAEgAAAAAAAAAAAAAAAAAAAAAAAABcAwAAEgAQAC4UAAAAAAAAQgEAAAAAAAAAU2NydDEubwBfX2FiaV90YWcAY3J0c3R1ZmYuYwBkZXJlZ2lzdGVyX3RtX2Nsb25lcwBfX2RvX2dsb2JhbF9kdG9yc19hdXgAY29tcGxldGVkLjAAX19kb19nbG9iYWxfZHRvcnNfYXV4X2ZpbmlfYXJyYXlfZW50cnkAZnJhbWVfZHVtbXkAX19mcmFtZV9kdW1teV9pbml0X2FycmF5X2VudHJ5AGRlYnVnZ2luZ19iaW4uYwBfX0ZSQU1FX0VORF9fAF9EWU5BTUlDAF9fR05VX0VIX0ZSQU1FX0hEUgBfR0xPQkFMX09GRlNFVF9UQUJMRV8AX19saWJjX3N0YXJ0X21haW5AR0xJQkNfMi4zNABfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAc3Rkb3V0QEdMSUJDXzIuMi41AF9lZGF0YQBmY2xvc2VAR0xJQkNfMi4yLjUAX2ZpbmkAX19zdGFja19jaGtfZmFpbEBHTElCQ18yLjQAcGlkX2NvdW50ZXIAc2V0YnVmQEdMSUJDXzIuMi41AGR1cDJAR0xJQkNfMi4yLjUAcGlwZUBHTElCQ18yLjIuNQByZWFkQEdMSUJDXzIuMi41AGZnZXRzQEdMSUJDXzIuMi41AF9fZGF0YV9zdGFydABnZGJzZXJ2ZXJfcGlkAF9fZ21vbl9zdGFydF9fAF9fZHNvX2hhbmRsZQBfSU9fc3RkaW5fdXNlZABraWxsQEdMSUJDXzIuMi41AG1hbGxvY0BHTElCQ18yLjIuNQByZWFkX3VudGlsAF9lbmQAZmRvcGVuQEdMSUJDXzIuMi41AF9fYnNzX3N0YXJ0AG1haW4AcnVuX2dkYgB3YWl0cGlkQEdMSUJDXzIuMi41AHBlcnJvckBHTElCQ18yLjIuNQBzZXBhcmF0b3IAZXhlY3ZwQEdMSUJDXzIuMi41AHNwcmludGZAR0xJQkNfMi4yLjUAZXhpdEBHTElCQ18yLjIuNQBfX1RNQ19FTkRfXwBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fY3hhX2ZpbmFsaXplQEdMSUJDXzIuMi41AF9pbml0AGZvcmtAR0xJQkNfMi4yLjUAc3Ryc3RyQEdMSUJDXzIuMi41AGZpbmRfbWF4X3BpZAAALnN5bXRhYgAuc3RydGFiAC5zaHN0cnRhYgAuaW50ZXJwAC5ub3RlLmdudS5wcm9wZXJ0eQAubm90ZS5nbnUuYnVpbGQtaWQALm5vdGUuQUJJLXRhZwAuZ251Lmhhc2gALmR5bnN5bQAuZHluc3RyAC5nbnUudmVyc2lvbgAuZ251LnZlcnNpb25fcgAucmVsYS5keW4ALnJlbGEucGx0AC5pbml0AC5wbHQuZ290AC5wbHQuc2VjAC50ZXh0AC5maW5pAC5yb2RhdGEALmVoX2ZyYW1lX2hkcgAuZWhfZnJhbWUALmluaXRfYXJyYXkALmZpbmlfYXJyYXkALmR5bmFtaWMALmRhdGEALmJzcwAuY29tbWVudAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAQAAAAIAAAAAAAAAGAMAAAAAAAAYAwAAAAAAABwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIwAAAAcAAAACAAAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAADYAAAAHAAAAAgAAAAAAAABoAwAAAAAAAGgDAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABJAAAABwAAAAIAAAAAAAAAjAMAAAAAAACMAwAAAAAAACAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAVwAAAPb//28CAAAAAAAAALADAAAAAAAAsAMAAAAAAAAoAAAAAAAAAAYAAAAAAAAACAAAAAAAAAAAAAAAAAAAAGEAAAALAAAAAgAAAAAAAADYAwAAAAAAANgDAAAAAAAAiAIAAAAAAAAHAAAAAQAAAAgAAAAAAAAAGAAAAAAAAABpAAAAAwAAAAIAAAAAAAAAYAYAAAAAAABgBgAAAAAAAA8BAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAcQAAAP///28CAAAAAAAAAHAHAAAAAAAAcAcAAAAAAAA2AAAAAAAAAAYAAAAAAAAAAgAAAAAAAAACAAAAAAAAAH4AAAD+//9vAgAAAAAAAACoBwAAAAAAAKgHAAAAAAAAQAAAAAAAAAAHAAAAAQAAAAgAAAAAAAAAAAAAAAAAAACNAAAABAAAAAIAAAAAAAAA6AcAAAAAAADoBwAAAAAAAPAAAAAAAAAABgAAAAAAAAAIAAAAAAAAABgAAAAAAAAAlwAAAAQAAABCAAAAAAAAANgIAAAAAAAA2AgAAAAAAADgAQAAAAAAAAYAAAAYAAAACAAAAAAAAAAYAAAAAAAAAKEAAAABAAAABgAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAGwAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACcAAAAAQAAAAYAAAAAAAAAIBAAAAAAAAAgEAAAAAAAAFABAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAApwAAAAEAAAAGAAAAAAAAAHARAAAAAAAAcBEAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAALAAAAABAAAABgAAAAAAAACAEQAAAAAAAIARAAAAAAAAQAEAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAC5AAAAAQAAAAYAAAAAAAAAwBIAAAAAAADAEgAAAAAAAG4GAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAvwAAAAEAAAAGAAAAAAAAADAZAAAAAAAAMBkAAAAAAAANAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAMUAAAABAAAAAgAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADNAAAAAQAAAAIAAAAAAAAAACEAAAAAAAAAIQAAAAAAAEwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA2wAAAAEAAAACAAAAAAAAAFAhAAAAAAAAUCEAAAAAAAAMAQAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAOUAAAAOAAAAAwAAAAAAAAAgPQAAAAAAACAtAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADxAAAADwAAAAMAAAAAAAAAKD0AAAAAAAAoLQAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA/QAAAAYAAAADAAAAAAAAADA9AAAAAAAAMC0AAAAAAADwAQAAAAAAAAcAAAAAAAAACAAAAAAAAAAQAAAAAAAAAKsAAAABAAAAAwAAAAAAAAAgPwAAAAAAACAvAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAGAQAAAQAAAAMAAAAAAAAAAEAAAAAAAAAAMAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAEAAAgAAAADAAAAAAAAACBAAAAAAAAAIDAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAABEBAAABAAAAMAAAAAAAAAAAAAAAAAAAACAwAAAAAAAAKwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAABQMAAAAAAAANAFAAAAAAAAHQAAABIAAAAIAAAAAAAAABgAAAAAAAAACQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAIDYAAAAAAABpAwAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAIk5AAAAAAAAGgEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA="
DOCKER_SETUP = f'''

# DOCKER SETUP BY docker-debugger
COPY {BINARY_NAME} /{BINARY_NAME}
RUN apt update
RUN apt install -y gdbserver

'''

# Routine to restore the backup if -r (--restore-backup) argument is passed
def restore():
    restored = False
    try:
        f1 = open("Dockerfile.bak", "r")
        f2 = open("docker-compose.bak", "r")
        dockerfile = f1.read()
        docker_compose = f2.read()
        f1.close()
        f2.close()
        f = open("Dockerfile", "w")
        f.write(dockerfile)
        f.close()
        f = open("docker-compose.yml", "w")
        f.write(docker_compose)
        f.close()
        print("Backup successfully restored")
        restored = True
        exit(0)
    except:
        if restored == True:
            exit()
        print("Backup restore failed")
        exit(1)

# Parse command line arguments
def arg_parser():
    global DOCKER_PATH, GDBSERVER_PORT, CHALLENGE_PATH
    if len(sys.argv) < 2:
        print(HELP)
        exit(1)
    positional_arguments = 0
    for i in range(1, len(sys.argv)):
        arg = sys.argv[i]

        if arg == "-h" or arg == "--help":
            print(HELP)
            exit()

        elif arg == "-r" or arg == "--restore-backup":
            restore()

        elif arg == "-u" or arg == "--docker-path":
            if (i + 1) >= len(sys.argv):
                print(HELP)
                exit(1)
            path = sys.argv[i + 1]
            if os.path.exists(path):
                DOCKER_PATH = path
            else:
                print("Invalid path!")
                exit(1)
        
        elif arg == "-p" or arg == "--port":
            if (i + 1) >= len(sys.argv):
                print(HELP)
                exit(1)
            port = sys.argv[i + 1]
            try:
                port = int(port)
            except:
                print("Port must be an integer!")
                exit(1)
            if port <= 0 or port > 65535:
                print("Port must be in range 1-65535")
                exit(1)
            GDBSERVER_PORT = port
        
        else:
            if positional_arguments >= POSITIONAL_ARGUMENTS:
                print(HELP)
                exit(1)
            if positional_arguments == 0:
                CHALLENGE_PATH = arg
            positional_arguments = positional_arguments + 1


# Parse the socat command runned in the Dockerfile
def docker_cmd_arg_extract(command):
    # Put all the command in one line to parse it easily
    inline_command = command.split("\\")
    for i in range(len(inline_command)):
        inline_command[i] = inline_command[i].strip() + " "
    inline_command = "".join(inline_command)

    # Construct a list containing the arguments
    command_args = inline_command[len("CMD socat "):]
    args_list = ["socat"]
    new_arg = ""
    in_string = False
    for car in command_args:
        if car == " " and in_string == False:
            args_list.append(new_arg)
            new_arg = ""
            continue
        elif car == '"':
            in_string = not in_string
        new_arg = new_arg + car
    if new_arg != "":
        args_list.append(new_arg)
    return args_list

# Add the socat verbose option (-d -d) to the arguments
def add_verbose(arguments):
    new_args = []
    new_args.append(arguments[0])
    new_args.append("-d")
    new_args.append("-d")
    new_args = new_args + arguments[1:]
    return new_args

# Add the option field with value value to the docker-compose passed as a string in compose
def add_compose_option(compose ,field, value):
    field_indentation = ""
    value_identation = ""
    is_value = False
    for line in compose.split("\n"):
        if is_value == True:
            value_identation = line[:line.find("-")]
            break
        if "ports:" in line:
            field_indentation = line[:line.find("ports:")]
            is_value = True

    new_compose = compose[:compose.find(f"{field_indentation}ports:")] +\
                  f"{field_indentation}{field}:\n{value_identation}- {value}\n" +\
                  compose[compose.find(f"{field_indentation}ports:"):]
    return new_compose
    

def main():
    arg_parser()

    # Check for Dockerfile
    dockerfile_path = os.path.join(DOCKER_PATH, "Dockerfile")
    compose_yml_path = os.path.join(DOCKER_PATH, "docker-compose.yml")
    compose_yaml_path = os.path.join(DOCKER_PATH, "docker-compose.yaml")

    if not os.path.isfile(dockerfile_path):
        print("Dockerfile not found in the specified path.")
        exit(1)

    # Rename docker-compose.yaml to docker-compose.yml
    if os.path.isfile(compose_yaml_path) and not os.path.isfile(compose_yml_path):
        os.rename(compose_yaml_path, compose_yml_path)

    if not os.path.isfile(compose_yml_path):
        print("docker-compose.yml not found in the specified path.")
        exit(1)

    # Open Dockerfile
    f = open(dockerfile_path, "r")
    dockerfile = f.read()
    f.close()

    # Check if Dockerfile has been patched yet
    if "# DOCKER SETUP BY docker-debugger" in dockerfile:
        print("Project alredy patched, restore the backup before using docker-debugger again")
        exit(1)

    # Check if Dockerfile use socat
    command = dockerfile[dockerfile.find("CMD "):]
    if not "socat" in command:
        print("This docker doesn't use socat...")
        exit(1)
    
    # Parse the command executed by Dockerfile and add verbose option to the socat command
    args_list = docker_cmd_arg_extract(command)
    args_list = add_verbose(args_list)

    # Write arguments to pass them as arguments in the new Dockerfile command
    cli_args = ""
    for elem in args_list:
        cli_args = cli_args + " " + elem

    # Generating debugging_bin
    f = open(f"{BINARY_NAME}", "wb")
    f.write(base64.b64decode(BINARY))
    f.close()
    os.chmod(f"{BINARY_NAME}", 0o755)


    # Write a backup of Dockerfile in Dockerfile.bak
    f = open(dockerfile_path + ".bak", "w")
    f.write(dockerfile)
    f.close()

    # patch Dockerfile
    patched_command = f"CMD /{BINARY_NAME} {CHALLENGE_PATH} {cli_args}"
    nuovo = dockerfile.split("CMD")
    nuovo[0] = nuovo[0] + DOCKER_SETUP + "# OLD EXECUTION COMMAND\n" + "# CMD"
    nuovo[1] =  nuovo[1].replace("\n", "\n#") + "\n\n" + patched_command
    nuovo = "".join(nuovo)
    f = open("Dockerfile", "w")
    f.write(nuovo)
    f.close()

    # Write backup for docker-compose.yml in docker-compose.bak
    f = open(compose_yml_path, "r")
    docker_compose = f.read()
    f.close()
    f = open(compose_yml_path.replace("yml", "bak"), "w")
    f.write(docker_compose)
    f.close()

    # Patch docker-compose.yml
    nuovo = docker_compose.split("ports:")
    identation = nuovo[1].split("\n")[1]
    identation = identation[:identation.find("-")]
    nuovo[0] = nuovo[0] + "ports:\n"
    nuovo[1] = (identation + f"- {GDBSERVER_PORT}:{GDBSERVER_PORT}") + nuovo[1]
    nuovo = "".join(nuovo)
    nuovo = add_compose_option(nuovo, "cap_add", "SYS_PTRACE")
    nuovo = add_compose_option(nuovo, "security_opt", "seccomp=unconfined")
    f = open(compose_yml_path, "w")
    f.write(nuovo)
    f.close()

if __name__ == "__main__":
    main()